sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_f7187a59b136_key -iv $encrypted_f7187a59b136_iv -in multi-k8s-clusterSP-20200630142738.pem.enc -out multi-k8s-clusterSP-20200630142738.pem -d
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - az aks install-cli
  - az login --service-principal -u http://multi-k8s-clusterSP-20200630142738 -p multi-k8s-clusterSP-20200630142738.pem --tenant 67a8e67d-04e4-423c-bb98-cdf754992eb1