apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pizzahat-biz-tls
  namespace: default
spec:
  secretName: pizzahat-biz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pizzahat.biz
  dnsNames:
    - pizzahat.biz
    - www.pizzahat.biz